### ISSUE TITLE
Super_L key issue on Elementary OS Freya

### ISSUE THREAD

**Issue by leoheck** [iberianpig/xSwipe#17]
How to use "{Super_L}" on Freya? I can't make it work and all shortcuts use the Super_L key!

**Comment by iberianpig** [comment]
Thanks for your report. I'll check soon.

**Comment by leoheck** [comment]
The issue is considering the instructions on the README.md. 
The commands below are not giving me the current repository files.

```bash
$ cd ~
$ wget https://github.com/iberianpig/xSwipe/archive/master.zip
$ unzip master.zip
```

When I downloaded the current version of the repository everything works just fine, except for the smartwatch message on line 111 so I did replace it by "pantheon"
