### ISSUE TITLE
It just don't workout 

### ISSUE THREAD

**Issue by buschco** [iberianpig/xSwipe#29]
I followed all steps with getting an error and it don't work.

Thats my output wenn I start  the script.
colin@colin-dellxps13:~$ perl ~/xSwipe-master/xSwipe.pl
Smartmatch is experimental at /home/colin/xSwipe-master/xSwipe.pl line 121.

###                  '    LeftEdge                = 1583
',
###                  '    RightEdge               = 5359
',
###                  '    TopEdge                 = 1371
',
###                  '    BottomEdge              = 4481
'
### $session_name: 'ubuntu'
Please help me.
I have a Dell XPS 13 running Ubuntu 14.04

**Comment by iberianpig** [comment]
please try below command

    sudo apt-get install libmatch-simple-perl

**Comment by AwanishKr** [comment]
I am also getting the exact error, someone please reply if they have worked it out.
