### ISSUE TITLE
Install on Ubuntu 14.04 - Unity

### ISSUE THREAD

**Issue by Gocht** [iberianpig/xSwipe#30]
I have seen videos of this working on other machines, really a good job, thanks for this, but, is there a way to install this on Ubuntu 14.04 with Unity? I have been looking for a while on internet and I am not able to install this. 

I got this:

    Can't locate Smart/Comments.pm in @INC (you may need to install the Smart::Comments module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /home/user/xSwipe-master/xSwipe.pl line 15.
    BEGIN failed--compilation aborted at /home/user/xSwipe-master/xSwipe.pl line 15.

**Comment by GooKv** [comment]
Try
```
sudo apt-get install libsmart-comments-perl
```

**Comment by Gocht** [comment]
I think this is working now. Do I need to run xSwipe everytime I want to use multigesture? How do I configure actions for gestures?

**Comment by iberianpig** [comment]
see #31
