### ISSUE TITLE
How to Forever run xSwipe

### ISSUE THREAD

**Issue by Gocht** [iberianpig/xSwipe#31]
I've succesfully installed xSwipe and Touchegg in Ubuntu 14.04, I have configured the action I wanted, 3 fingers swipe between workspaces (it is not working perfectly but I think I need some practice), but I have to run xSwipe in a console to use this feature, how can I make this start on boot an run automatically?

**Comment by Bastianowicz** [comment]
just add your command to your autorun configuration such as rc.local. see /etc/rc.local for this. you need to edit it as root. worked for me.

**Comment by iberianpig** [comment]
thank you @Bastianowicz
