### ISSUE TITLE
3 fingers down does not execute the defined keystrokes

### ISSUE THREAD

**Issue by kyle-jennings** [iberianpig/xSwipe#40]
The default 3 finger down should execute ctrl+alt+down to move my workspace down, and while the terminal does in fact show those key strokes:

```
### @event_string: [
###                  'LCT',
###                  'LAL',
###                  'DOW'
###                ]

```

Nothing happens. 3 fingers up/left/right all work as expected but down does not.

Running ubuntu 16.04 on an Asus Zenbook ux305L

**Comment by iberianpig** [comment]
see:
https://github.com/iberianpig/xSwipe/wiki/Customize-eventKey.cfg#update-at-20140713

2016年5月26日(木) 6:51 Kyle Jennings <notifications@github.com>:
