### ISSUE TITLE
the instruction of "synclient" 

### ISSUE THREAD

**Issue by Turtle-Duck** [iberianpig/xSwipe#44]
My computer can't run your script because:

 $session_name: 'ubuntu'
synclient: invalid option -- 'm'
Usage: synclient [-h] [-l] [-V] [-?] [var1=value1 [var2=value2] ...]
  -l List current user settings
  -V Print synclient version string and exit
  -? Show this help message
  var=value  Set user parameter 'var' to 'value'.
init

I am sorry but how can i fix it? I am love to use it.

**Comment by iberianpig** [comment]
see https://github.com/iberianpig/xSwipe/blob/master/README.md#install-older-version-synaptics-driver-that-is-compatible-with-xswipe

**Comment by Turtle-Duck** [comment]
thanks！
