### ISSUE TITLE
syndaemon is started, which may be unnecessary

### ISSUE THREAD

**Issue by JJK96** [iberianpig/xSwipe#50]
I noticed that xSwipe starts syndaemon. 
When I kill syndaemon however (to play a game using touchpad). The gestures continue to work. 
My question:
Is it really necessary to start syndaemon for xSwipe?

**Comment by iberianpig** [comment]
OK, I'll stop syndaemon. I think so.

2016年11月2日(水) 17:15 JJK96 <notifications@github.com>:
